# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Budget_meal', models.IntegerField(verbose_name='伙食费（外币）')),
                ('Budget_accom', models.IntegerField(verbose_name='住宿费（外币）')),
                ('Budget_work', models.IntegerField(verbose_name='公杂费（外币）')),
                ('Budget_transition', models.IntegerField(blank=True, null=True, verbose_name='城际间交通费（外币）')),
                ('Budget_conference', models.IntegerField(blank=True, null=True, verbose_name='会议注册费（外币）')),
            ],
        ),
        migrations.CreateModel(
            name='CardPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_num', models.CharField(max_length=20, verbose_name='课题卡号')),
                ('total', models.FloatField(verbose_name='国际交流费总金额')),
                ('current', models.FloatField(verbose_name='剩余国际交流费金额')),
                ('amount', models.FloatField(verbose_name='报销金额')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CityInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='')),
                ('short_meal', models.IntegerField(blank=True, null=True, verbose_name='伙食费标准')),
                ('short_accom', models.IntegerField(blank=True, null=True, verbose_name='住宿费标准')),
                ('short_work', models.IntegerField(blank=True, null=True, verbose_name='公杂费标准')),
                ('study_high', models.IntegerField(blank=True, null=True, verbose_name='高级访问标准')),
                ('study_middle', models.IntegerField(blank=True, null=True, verbose_name='中级访问标准')),
                ('study_student', models.IntegerField(blank=True, null=True, verbose_name='研究学生标准')),
            ],
        ),
        migrations.CreateModel(
            name='CountryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='国家简称')),
                ('cash', models.CharField(choices=[(1, '美元'), (2, '欧元'), (3, '英镑'), (4, '日元')], max_length=1, verbose_name='外汇种类')),
                ('visa_requirement', models.TextField(verbose_name='办理签证所需材料')),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_mobile', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=200, verbose_name='英文项目名称')),
                ('time_leave', models.DateField(verbose_name='离开中国国境日期')),
                ('time_back', models.DateField(verbose_name='返回中国国境日期')),
                ('Task', models.CharField(max_length=500, verbose_name='出访目的250字')),
                ('mission', models.CharField(max_length=1000, verbose_name='出访任务500字')),
                ('research_delegation', models.CharField(choices=[('A', '教学科研类团组'), ('B', '非教学科研类团组')], default='A', max_length=1, verbose_name='是否为教学科研团组')),
                ('delegation_tag', models.CharField(choices=[('01', '合作研究'), ('02', '学术访问'), ('03', '出席国际会议'), ('04', '教学活动'), ('05', '科学观测'), ('06', '科学考察'), ('07', '科研仪器调试'), ('08', '科技展览'), ('09', '出席国际组织活动'), ('10', '人才招聘'), ('11', '其他')], max_length=2, verbose_name='团组类型')),
                ('time_arrangement', models.CharField(max_length=1000, verbose_name='详细日程安排')),
                ('finacial', models.CharField(max_length=100, verbose_name='课题卡号, 多个课题卡以分号隔开')),
                ('budget_abroad', models.IntegerField(verbose_name='境外预算')),
                ('budget_internal', models.IntegerField(verbose_name='国内预算')),
                ('process', models.CharField(choices=[('01', '填表'), ('02', '公示'), ('03', '申请表、arp所内审批'), ('04', 'arp院审批'), ('05', '护照留指纹'), ('06', '办理新护照'), ('07', '准备签证材料'), ('08', '签证过程中'), ('09', '申领外汇'), ('10', '执行出访任务'), ('11', '出访总结'), ('12', '事后公示'), ('13', '外汇核销'), ('14', '人民币报销'), ('15', '完结')], default='01', max_length=2, verbose_name='团组进程')),
                ('unexpected', models.CharField(choices=[('1', '正常'), ('2', '全团取消出访'), ('3', '部分成员取消出访')], default='1', max_length=1, verbose_name='团组特殊情况')),
                ('log', models.TextField(blank=True, verbose_name='进度记录')),
                ('sign', models.CharField(blank=True, max_length=200, unique=True, verbose_name='标识')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateField(verbose_name='邀请信上开始时间')),
                ('time_end', models.DateField(verbose_name='邀请信上结束时间')),
                ('invitor', models.CharField(max_length=100, verbose_name='邀请人')),
                ('tel', models.CharField(max_length=30, verbose_name='邀请方电话')),
                ('address', models.CharField(max_length=400, verbose_name='邀请方英文地址')),
                ('Institue_CH', models.CharField(max_length=200, verbose_name='邀请单位中文名称')),
                ('Insitute_EN', models.CharField(max_length=200, verbose_name='邀请单位英文名称')),
                ('invitation_letter', models.FileField(upload_to='upload/%Y/%m/', verbose_name='')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foreign_App.Delegation')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foreign_App.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PassportInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=15, verbose_name='护照号码')),
                ('date_issue', models.DateField(blank=True, null=True, verbose_name='颁发日期')),
                ('date_expire', models.DateField(blank=True, null=True, verbose_name='过期日期')),
                ('issue_office', models.CharField(max_length=15, verbose_name='发证机关')),
                ('issue_place', models.CharField(max_length=15, verbose_name='发证地点')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name='借出日期')),
                ('date_back', models.DateField(blank=True, null=True, verbose_name='归还日期')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_permit', models.FileField(upload_to='upload/%Y/%m/', verbose_name='所内审批表扫描件')),
                ('cas_permit', models.FileField(upload_to='upload/%Y/%m/', verbose_name='院批件')),
                ('cas_permit_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='院批件文号')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foreign_App.Delegation')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('tel', models.CharField(max_length=12, verbose_name='电话')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='性别')),
                ('department', models.CharField(max_length=30, verbose_name='所在部门')),
                ('ID_num', models.CharField(max_length=18, verbose_name='18位身份证号')),
                ('Place_of_Birth', models.CharField(choices=[('01', '上海市'), ('02', '北京市'), ('03', '山东省'), ('04', '黑龙江省'), ('05', '吉林省'), ('06', '辽宁省'), ('07', '河北省'), ('08', '内蒙古自治区'), ('09', '天津市'), ('10', '山西省'), ('11', '陕西省'), ('12', '甘肃省'), ('13', '新疆维吾尔自治区'), ('14', '青海省'), ('15', '河南省'), ('16', '宁夏回族自治区'), ('17', '西藏自治区'), ('18', '四川省'), ('19', '湖北省'), ('20', '湖南省'), ('21', '江苏省'), ('22', '浙江省'), ('23', '安徽省'), ('24', '福建省'), ('25', '云南省'), ('26', '贵州省'), ('27', '广东省'), ('28', '广西壮族自治区'), ('29', '重庆市'), ('30', '海南省'), ('31', '江西省'), ('32', '境外')], max_length=2, verbose_name='出生地（省）')),
                ('Date_of_Birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('duty', models.CharField(choices=[('A', '所长'), ('B', '副所长'), ('C', '书记'), ('D', '无')], max_length=1, verbose_name='职务')),
                ('identity', models.CharField(choices=[('A', '研究员'), ('B', '副研究员'), ('C', '助理研究员'), ('D', '工程师'), ('E', '高级工程师'), ('F', '正高级工程师'), ('G', '博士后、在读学生')], max_length=1, verbose_name='对外身份')),
                ('race', models.CharField(choices=[('01', '汉族'), ('02', '满族'), ('03', '回族'), ('04', '藏族'), ('05', '壮族'), ('06', '其他')], max_length=2, verbose_name='民族')),
                ('political_identity', models.CharField(choices=[('01', '中共党员'), ('02', '中共预备党员'), ('03', '共青团员'), ('04', '民革党员'), ('05', '民盟盟员'), ('06', '民建会员'), ('07', '民进会员'), ('08', '农工党党员'), ('09', '致公党党员'), ('10', '九三学社社员'), ('11', '台盟盟员'), ('12', '无党派人士'), ('13', '群众')], max_length=2, verbose_name='政治面貌')),
                ('securety', models.CharField(choices=[('A', '绝密'), ('B', '机密'), ('C', '秘密'), ('D', '不涉密')], max_length=1, verbose_name='涉密等级')),
                ('status_health', models.CharField(choices=[('A', '健康'), ('B', '一般'), ('C', '较差')], max_length=1, verbose_name='健康状况')),
                ('emergency_contact_name', models.CharField(max_length=10, verbose_name='紧急联系人姓名')),
                ('emergency_contact_tel', models.CharField(max_length=11, verbose_name='紧急联系人电话')),
                ('sign', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elegation_tag', models.CharField(choices=[('01', '合作研究'), ('02', '学术访问'), ('03', '出席国际会议'), ('04', '教学活动'), ('05', '科学观测'), ('06', '科学考察'), ('07', '科研仪器调试'), ('08', '科技展览'), ('09', '出席国际组织活动'), ('10', '人才招聘'), ('11', '其他')], max_length=2, verbose_name='团组类型')),
                ('date_out', models.DateField(verbose_name='拟出访日期')),
                ('days_out', models.IntegerField(verbose_name='拟出访天数')),
                ('finacial', models.IntegerField(verbose_name='所需经费额')),
                ('country', models.ManyToManyField(to='Foreign_App.CountryInformation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foreign_App.PersonalInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_meal_yan', models.FloatField(verbose_name='伙食费(人民币)')),
                ('fee_accom_uam', models.FloatField(verbose_name='住宿费(人民币)')),
                ('fee_work_yan', models.FloatField(verbose_name='工杂费(人民币)')),
                ('fee_transition_yan', models.FloatField(verbose_name='城际间交通费(人民币)')),
                ('fee_conference_yan', models.FloatField(verbose_name='会议注册费(人民币)')),
                ('cash_check', models.FileField(upload_to='upload/%Y/%m/', verbose_name='外汇核销表')),
                ('fee_international', models.FloatField(verbose_name='国际旅费')),
                ('fee_insurance', models.FloatField(verbose_name='保险费')),
                ('fee_visa', models.FloatField(verbose_name='签证费')),
                ('fee_transition', models.FloatField(verbose_name='市内交通费')),
                ('total', models.FloatField(verbose_name='合计')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_leave', models.DateField(verbose_name='实际离境日期')),
                ('date_back', models.DateField(verbose_name='实际抵境日期')),
                ('summary', models.TextField(verbose_name='出访总结')),
                ('passport', models.FileField(upload_to='upload/%Y/%m/', verbose_name='护照、出入境章扫描件')),
                ('receipt', models.FileField(upload_to='upload/%Y/%m/', verbose_name='发票扫描件')),
                ('picture', models.FileField(upload_to='upload/%Y/%m/', verbose_name='工作照片')),
                ('fee_meal', models.IntegerField(verbose_name='实际伙食费（外币）')),
                ('fee_accom', models.FloatField(verbose_name='实际住宿费（外币）')),
                ('fee_work', models.IntegerField(verbose_name='实际工杂费（外币）')),
                ('fee_transition', models.FloatField(verbose_name='实际城际间交通费（外币）')),
                ('fee_conference', models.FloatField(verbose_name='实际会议注册费（外币）')),
                ('Delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foreign_App.Delegation')),
                ('cities', models.ManyToManyField(to='Foreign_App.CityInformation', verbose_name='实际访问城市')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateField(verbose_name='提交申请时间')),
                ('public_time', models.DateField(verbose_name='公示时间')),
                ('arp_input', models.DateField(verbose_name='arp填写时间')),
                ('inner_permit', models.DateField(verbose_name='所内审批时间')),
                ('arp_to_cas', models.DateField(verbose_name='arp上报时间')),
                ('cas_permit', models.DateField(verbose_name='批件下达时间')),
                ('finger_print_date', models.DateField(verbose_name='外办留指纹时间')),
                ('new_passport_date', models.DateField(verbose_name='办理新护照时间')),
                ('visa_infee_date', models.DateField(verbose_name='交签证费时间')),
                ('visa_in_date', models.DateField(verbose_name='送办签证时间')),
                ('visa_finger_date', models.DateField(verbose_name='领馆留指纹时间')),
                ('visa_out_date', models.DateField(verbose_name='获得批件时间')),
                ('visa_fee_date', models.DateField(verbose_name='退还签证费时间')),
                ('cash_date', models.DateField(verbose_name='申请外事借款时间')),
                ('summary_date', models.DateField(verbose_name='提交总结时间')),
                ('summary_pub_date', models.DateField(verbose_name='事后公示时间')),
                ('passport_back_date', models.DateField(verbose_name='归还护照时间')),
                ('cash_check_date', models.DateField(verbose_name='外汇核销时间')),
                ('rmb_reimburse_date', models.DateField(verbose_name='完成报销时间')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foreign_App.Delegation')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisaInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, verbose_name='国家')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='颁发日期')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='过期日期')),
                ('visa_class', models.CharField(choices=[('A', '一次入境签证'), ('B', '多次入境签证')], max_length=1, verbose_name='签证类型')),
                ('visa_file', models.FileField(upload_to='upload/%Y/%M/', verbose_name='签证扫描件')),
                ('sign', models.CharField(max_length=100, unique=True)),
                ('Passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foreign_App.PassportInformation')),
            ],
        ),
        migrations.AddField(
            model_name='passportinformation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foreign_App.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='invitationinformation',
            name='member',
            field=models.ManyToManyField(to='Foreign_App.PersonalInformation', verbose_name='被邀请人'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='Members',
            field=models.ManyToManyField(to='Foreign_App.PersonalInformation', verbose_name='出访人员'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='contact_name',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delegation',
            name='country',
            field=models.ManyToManyField(to='Foreign_App.CountryInformation', verbose_name='出访国家'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='destination',
            field=models.ManyToManyField(to='Foreign_App.CityInformation', verbose_name='出访目的地'),
        ),
        migrations.AddField(
            model_name='cityinformation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foreign_App.CountryInformation'),
        ),
        migrations.AddField(
            model_name='cardpay',
            name='Reim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foreign_App.Reimbursement'),
        ),
        migrations.AddField(
            model_name='budgetinformation',
            name='Delegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foreign_App.Delegation'),
        ),
    ]
